"""Du an nhieu cong trinh - ho_so_session_hang_muc

Revision ID: 207ea880a437
Revises: ed3d2b2ab2d7
Create Date: 2026-08-25 15:36:11.544795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207ea880a437'
down_revision = 'ed3d2b2ab2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ho_so_session_hang_muc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ten_hang_muc', sa.String(length=255), nullable=False),
    sa.Column('occ', sa.String(length=30), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('basements', sa.Integer(), nullable=True),
    sa.Column('semi_basements', sa.Integer(), nullable=True),
    sa.Column('area_floor', sa.Float(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('h_fire', sa.Float(), nullable=True),
    sa.Column('kids', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('hazard', sa.String(length=1), nullable=True),
    sa.Column('gara_kin', sa.String(length=10), nullable=True),
    sa.Column('gara_kc12', sa.String(length=10), nullable=True),
    sa.Column('gara_bcl', sa.String(length=10), nullable=True),
    sa.Column('gara_cap_s', sa.String(length=10), nullable=True),
    sa.Column('ppl_floor', sa.Integer(), nullable=True),
    sa.Column('ext_level', sa.String(length=10), nullable=True),
    sa.Column('hanh_lang_dai_nhat', sa.Float(), nullable=True),
    sa.Column('chieu_cao_ke_hang', sa.Float(), nullable=True),
    sa.Column('co_be_xang_dau_ngoai_troi', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ho_so_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ho_so_session_hang_muc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ho_so_session_hang_muc_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session_hang_muc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ho_so_session_hang_muc_session_id'))

    op.drop_table('ho_so_session_hang_muc')
    # ### end Alembic commands ###
