"""add email verification, credit ledger, topup request (Batch 5A)

Revision ID: 33a95593a87d
Revises: 7269076b80f2
Create Date: 2026-08-01 21:20:51.756006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a95593a87d'
down_revision = '7269076b80f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_credit_ledger_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('email_verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_token_user_id'), ['user_id'], unique=False)

    op.create_table('topup_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=40), nullable=False),
    sa.Column('amount_vnd', sa.Integer(), nullable=False),
    sa.Column('credits_to_grant', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topup_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topup_request_reference_code'), ['reference_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_topup_request_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('topup_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topup_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_topup_request_reference_code'))

    op.drop_table('topup_request')
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_token_token_hash'))

    op.drop_table('email_verification_token')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_ledger_user_id'))
        batch_op.drop_index('ix_credit_ledger_user_created')

    op.drop_table('credit_ledger')
    # ### end Alembic commands ###
