"""add ho_so_session_quy_mo (Quy mo form A)

Revision ID: 4503ab6017ba
Revises: 4ca63b0c73f2
Create Date: 2026-08-02 16:03:07.893094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4503ab6017ba'
down_revision = '4ca63b0c73f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ho_so_session_quy_mo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('occ', sa.String(length=30), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('basements', sa.Integer(), nullable=True),
    sa.Column('semi_basements', sa.Integer(), nullable=True),
    sa.Column('area_floor', sa.Float(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('h_fire', sa.Float(), nullable=True),
    sa.Column('kids', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('hazard', sa.String(length=1), nullable=True),
    sa.Column('gara_kin', sa.String(length=10), nullable=True),
    sa.Column('gara_kc12', sa.String(length=10), nullable=True),
    sa.Column('gara_bcl', sa.String(length=10), nullable=True),
    sa.Column('gara_cap_s', sa.String(length=10), nullable=True),
    sa.Column('ppl_floor', sa.Integer(), nullable=True),
    sa.Column('ext_level', sa.String(length=10), nullable=True),
    sa.Column('hanh_lang_dai_nhat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ho_so_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ho_so_session_quy_mo_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ho_so_session_quy_mo_session_id'))

    op.drop_table('ho_so_session_quy_mo')
    # ### end Alembic commands ###
