"""add ho_so_session (Batch 5A sub-buoc 2)

Revision ID: 4ca63b0c73f2
Revises: 33a95593a87d
Create Date: 2026-08-02 04:29:19.118481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca63b0c73f2'
down_revision = '33a95593a87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ho_so_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('files_used', sa.Integer(), nullable=False),
    sa.Column('forms_used', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['credit_ledger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ho_so_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ho_so_session_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ho_so_session_user_id'))

    op.drop_table('ho_so_session')
    # ### end Alembic commands ###
