"""add composite index on usage_log for quota queries

Revision ID: 7269076b80f2
Revises: 9ba0353a8591
Create Date: 2026-08-01 14:47:46.373807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7269076b80f2'
down_revision = '9ba0353a8591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.create_index('ix_usage_log_user_api_created', ['user_id', 'api_name', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_log_user_api_created')

    # ### end Alembic commands ###
