"""add daily_quota to users

Revision ID: 9ba0353a8591
Revises: 839bc5c191d6
Create Date: 2026-07-31 04:41:27.162791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba0353a8591'
down_revision = '839bc5c191d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_quota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_quota')

    # ### end Alembic commands ###
