"""quy_mo them bac chiu lua, cap S, thong tin du an

Revision ID: c8b7a42b2708
Revises: d5279e3f3aec
Create Date: 2026-09-04 14:49:30.302928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b7a42b2708'
down_revision = 'd5279e3f3aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bac_chiu_lua', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cap_nguy_hiem_chay_ket_cau', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ten_cong_trinh', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('dia_diem_xay_dung', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('chu_dau_tu', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('dia_chi_chu_dau_tu', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('don_vi_tu_van_thiet_ke', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('so_ngay_pc11', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ma_ho_so', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tong_muc_dau_tu', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('thanh_phan_ho_so', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.drop_column('thanh_phan_ho_so')
        batch_op.drop_column('tong_muc_dau_tu')
        batch_op.drop_column('ma_ho_so')
        batch_op.drop_column('so_ngay_pc11')
        batch_op.drop_column('don_vi_tu_van_thiet_ke')
        batch_op.drop_column('dia_chi_chu_dau_tu')
        batch_op.drop_column('chu_dau_tu')
        batch_op.drop_column('dia_diem_xay_dung')
        batch_op.drop_column('ten_cong_trinh')
        batch_op.drop_column('cap_nguy_hiem_chay_ket_cau')
        batch_op.drop_column('bac_chiu_lua')

    # ### end Alembic commands ###
