"""Form A goc Phan 0 - pham vi de nghi va ha tang hien huu

Revision ID: d5279e3f3aec
Revises: 207ea880a437
Create Date: 2026-08-26 09:43:24.068269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5279e3f3aec'
down_revision = '207ea880a437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ho_so_session_ha_tang_hien_huu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ten_he_thong', sa.String(length=30), nullable=False),
    sa.Column('gcn_so', sa.String(length=100), nullable=False),
    sa.Column('gcn_ngay', sa.String(length=20), nullable=False),
    sa.Column('gcn_bo_sung_so', sa.String(length=100), nullable=True),
    sa.Column('gcn_bo_sung_ngay', sa.String(length=20), nullable=True),
    sa.Column('nghiem_thu_so', sa.String(length=100), nullable=False),
    sa.Column('nghiem_thu_ngay', sa.String(length=20), nullable=False),
    sa.Column('ghi_chu_ban_ve', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ho_so_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ho_so_session_ha_tang_hien_huu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ho_so_session_ha_tang_hien_huu_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pham_vi_de_nghi', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ho_so_session_quy_mo', schema=None) as batch_op:
        batch_op.drop_column('pham_vi_de_nghi')

    with op.batch_alter_table('ho_so_session_ha_tang_hien_huu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ho_so_session_ha_tang_hien_huu_session_id'))

    op.drop_table('ho_so_session_ha_tang_hien_huu')
    # ### end Alembic commands ###
